name: picamera-streaming-demo
version: '0.1'
summary: Simple package to stream web video from the RPi CSI camera interface
description: |
  A small demo snap, streaming video from a camera attached to the

  To watch the video stream go to http://<IP address of your Board>:8000/

grade: stable
confinement: strict


architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

apps:
  pistream:
    command: pistream
    daemon: simple
    plugs:
      - mount-observe
      - network
      - network-bind
      - opengl

parts:
  picamera:
    plugin: python
    python-version: python3
    python-packages:
      - picamera
    build-environment:
      - READTHEDOCS: 'True'
  pilibs:
    plugin: nil
    override-pull: |
      sudo add-apt-repository ppa:ubuntu-raspi2/ppa
      sudo apt-get update
    build-packages:
      - software-properties-common
    after: [ picamera ]
  pistream:
    source: .
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp pistream $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - libraspberrypi-bin
    after: [ pilibs ]
